### ISSUE TITLE
not able to install with league/omnipay:^3

### ISSUE THREAD

**Issue by salalaslam** [wasksofts/omnipay-mpesa#3]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: omnipay/common[v3.0.4, v3.0.2].
    - Can only install one of: omnipay/common[v3.0.2, v3.0.4].
    - Can only install one of: omnipay/common[v3.0.2, v3.0.4].
    - wasksofts/omnipay-mpesa v1.5 requires omnipay/common v3.0.2 -> satisfiable by omnipay/common[v3.0.2].
    - Installation request for wasksofts/omnipay-mpesa ^1.5 -> satisfiable by wasksofts/omnipay-mpesa[v1.5].
    - Installation request for omnipay/common (locked at v3.0.4) -> satisfiable by omnipay/common[v3.0.4].
```

**Comment by stevenkamanu** [comment]
please if you have any other package of omnipay/common v2 running on your vendor it may trigger this error .please you can try composer wasksofts/omnipay-mpesa instead

**Comment by stevenkamanu** [comment]
i have checked and no issue at all[
![wasksoft omnipay](https://user-images.githubusercontent.com/27777012/84548912-6ba03e80-ad0f-11ea-875b-6195a135cf02.PNG)
](url)

**Comment by stevenkamanu** [comment]
The downloaded packages via composer
![testc](https://user-images.githubusercontent.com/27777012/84549097-d94c6a80-ad0f-11ea-8e33-18ee7c7904ec.PNG)

**Comment by salalaslam** [comment]
> please if you have any other package of omnipay/common v2 running on your vendor it may trigger this error .please you can try composer wasksofts/omnipay-mpesa instead

I am installing this in a Laravel app and it appears that the conflict is with symfony/http-foundation.

**Comment by salalaslam** [comment]
if you can update your composer.json with
`"omnipay/common": "^3"`
instead of 3.0.2
